name: CI on windows

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
    - master
    tags:
    - '*'

jobs:
  linux:
    runs-on: windows-2016
    strategy:
      matrix:
        pattern: [cmake0,cmake1]
    steps:
    - uses: actions/checkout@v1
    - name: build and test
      env:
        APPVEYOR_SAVE_CACHE_ON_ERROR: true
        OPENSSL_ROOT: C:/OpenSSL-Win64
        PYTHON3: C:/Python37-x64/python.exe
        MPATH: C:/mingw-w64/x86_64-7.2.0-posix-seh-rt_v5-rev1/mingw64/bin;C:/msys64/usr/bin
        EVENT_TESTS_PARALLEL: 1
        EVENT_BUILD_PARALLEL: 10  
      shell: bash
      run: |
        pwd;
        BASE=`pwd`;
        mkdir ${BASE}/usr;
        # matrix config
        if [ ${{ matrix.pattern }} == cmake0 ]; then
          EVENT_BUILD_METHOD="cmake"
          EVENT_CMAKE_OPTIONS=""
          JOBS=1
        fi
        # build and test
        if ($env:EVENT_BUILD_METHOD -eq 'autotools') {
          echo "***1***"
        } else {
          md $env:BUILD_DIR 2> $null
          cd $env:BUILD_DIR
          $env:cmake_cmd="cmake -G 'Visual Studio 15 2017 Win64' .. $env:EVENT_CMAKE_OPTIONS"
          cmake --build . -j $env:EVENT_BUILD_PARALLEL -- /nologo /verbosity:minimal
          ctest --output-on-failure -j $env:EVENT_TESTS_PARALLEL
        }
